FROM elixir:1.19.5-otp-28

RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential git inotify-tools postgresql-client && \
    rm -rf /var/lib/apt/lists/*

RUN mix local.hex --force && mix local.rebar --force

ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    HEX_HOME=/hex \
    MIX_ENV=dev

WORKDIR /app
