import Config

parse_integer_env = fn env_name, default ->
  value = System.get_env(env_name, default)

  case Integer.parse(value) do
    {integer, ""} ->
      integer

    _ ->
      raise """
      environment variable #{env_name} must be an integer, got: #{inspect(value)}
      """
  end
end

parse_ip_env = fn env_name, default ->
  value = System.get_env(env_name, default)

  case :inet.parse_address(String.to_charlist(value)) do
    {:ok, ip_address} ->
      ip_address

    {:error, :einval} ->
      raise """
      environment variable #{env_name} must be a valid IPv4 or IPv6 address, got: #{inspect(value)}
      """
  end
end

# Configure your database
database_config =
  case System.get_env("DATABASE_URL") do
    nil ->
      [
        username: System.get_env("DATABASE_USER", "postgres"),
        password: System.get_env("DATABASE_PASSWORD", "postgres"),
        hostname: System.get_env("DATABASE_HOST", "localhost"),
        port: parse_integer_env.("DATABASE_PORT", "5432"),
        database: System.get_env("DATABASE_NAME", "water_dev")
      ]

    database_url ->
      [url: database_url]
  end

config :water,
       Water.Repo,
       database_config ++
         [
           stacktrace: true,
           show_sensitive_data_on_connection_error: true,
           pool_size: 10
         ]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :water, WaterWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [
    ip: parse_ip_env.("PHX_BIND_IP", "127.0.0.1"),
    port: parse_integer_env.("PORT", "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "ENRagInp9kSzbqfnVwPCCQVUgc5NsNo2MPFFZzGRRxYnzYAxL7LBuZKKjdkDg5k8",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:water, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:water, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :water, WaterWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/water_web/router\.ex$"E,
      ~r"lib/water_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :water, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
