import Config

session_max_age = Application.compile_env(:water, :authenticated_session_max_age, 2_592_000)

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :water, WaterWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

config :water, WaterWeb.Endpoint,
  session_options: [
    store: :cookie,
    key: "_water_key",
    signing_salt: "9mWDnYuj",
    encryption_salt: "rnFt1f06",
    same_site: "Lax",
    max_age: session_max_age,
    secure: true,
    http_only: true
  ]

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :water, WaterWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      hosts: ["localhost", "127.0.0.1"]
    ]
  ]

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
